### ISSUE TITLE
Uninstall not working

### ISSUE THREAD

**Issue by jlevers** [aacebedo/i3-xfce#4]
When I run `i3-xfce` uninstall, I get

```
Traceback (most recent call last):
  File "/usr/local/bin/i3-xfce", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'progressbar2>=2.0.0' distribution was not found and is required by i3-xfce
```

Do you know why that's happening? It seems that I need to install `progressbar2`, but I'm not sure if that's a pip package or an OS package...?

**Comment by aacebedo** [comment]
Solved with latest release
